### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by geektortoise**
Compile it with
`sudo docker build -t $DOCKER_IMAGE .`
then run with 
`sudo docker run -it --rm -v $OUTPUT_FOLDER:/opt/be_law_tools/output $DOCKER_IMAGE $OPTIONS`
Example : 
`sudo docker build -t be_law_tools .`
`sudo docker run -it --rm -v /tmp:/opt/be_law_tools/output be_law_tools --debug scan -s 2020-01-01`

### CODE REVIEW

**Comment by geektortoise** [comment]
Linked with #8

**Comment by tintamarre** [comment]
Works as expected !

```
be_law_tools (Dockerfile) $ docker run -it --rm -v /tmp:/opt/be_law_tools/output be_law_tools --debug scan -s 2020-01-01
Debug enabled
Wrote file /opt/be_law_tools/output/2019/2019031205.md
Wrote file /opt/be_law_tools/output/2019/2019031207.md
^C
Aborted!
```

**Comment by tintamarre** [comment]
Is there a specific reason to `git clone` the master repo instead of copying the files with `COPY . /opt/be_law_tools/` in the Dockerfile ?

**Comment by geektortoise** [comment]
It depends how you want to use it. 

If we have a DockerHub account, we can map the github tag and the dockerhub tag with a CI and I use the git clone way to ensure my Dockerfile is not "environment dependant" and so easiest to debug.

To have a dev environnement with my sources (for local tests before commiting), I use volume mapping
docker run -it --rm -v /MY_WORKDIR:/opt/be_law_tools/ be_law_tools --debug scan -s 2020-01-01

**Comment by tintamarre** [comment]
Thanks! Understood. :)

**Comment by tintamarre** [comment]
Je ferai un petit PR pour udpater le README.md à ce sujet.

**Pull request merged**
